### ISSUE TITLE
Errors in MathJax and KaTex inline

### ISSUE THREAD

**Issue by dishangti** [terrylinooo/githuber-md#193]
Something is wrong while using inline KaTex and MathJax. It could display correctly on preview screen, but it worked unproperly after posting. I'm using the newest WP version, and this problem happened even when using the examples on the plug-in.

**Comment by SnailDove** [comment]
I also have the same problem as the following pictures show! @dishangti, My environment is WordPress 5.3.3， Which is installed today (1st December, TimeZone: Asia/Shanghai), the more info about the environment references this repository, https://github.com/docker-library/wordpress.

![](http://qjctul5ib.hn-bkt.clouddn.com/mkdown_bug.jpg)

**Comment by slee981** [comment]
@dishangti  @SnailDove I've been looking for documentation of the proper syntax to add inline KaTex - no luck so far. Do you mind sharing how you're supposed to add inline Tex with this plugin? Block KaTex is working well. 

Any ideas on a workaround of this issue?

**Comment by lanyun1103** [comment]
I've tried a lot of things, but the problem on my site is that because underlining in markdown represents italics, a < em > tag is automatically added after publication, causing mathjax to fail to recognize $across two < em > tags. 
I have tried to correctly display the formula after escaping the underscore when editing markdown. If you are different from me, you can talk to me about how to solve it. Thank you.
我尝试过很多办法，在我的网站上问题在于，因为在markdown中下划代表斜体，发布后会自动添加<em>标签，导致mathjax无法识别跨越两个<em>标签的$。我试过在编辑markdown时转义下划线后可以正确显示公式，如果你和我情况不一样也可以交流一下如何解决，谢谢

**Comment by li-han-nu** [comment]
This problem has been [solved.](https://terryl.in/en/githuber-md-katex/?unapproved=832&moderation-hash=e6f2f1aade71cf145b3ae517fc577ebe#comment-832)
