### ISSUE TITLE
Forces Wordpress Gutenberg Editor

### ISSUE THREAD

**Issue by aPinix** [terrylinooo/githuber-md#249]
With your plugin installed it always forces Gutenberg editor on pages that don't have Markdown enabled by your plugin.

Tried:
- [WPBakery](https://wpbakery.com/) disable Gutenberg checkbox
- [Disable Gutenberg](https://wordpress.org/plugins/disable-gutenberg/) plugin
- [No Gutenberg – Disable Gutenberg Block Editor](https://wordpress.org/plugins/no-gutenberg/) plugin

Already have [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin installed

**Comment by eriktorsner** [comment]
I'm seeing the same issue but with WooCommerce products. When I activate this plugin, WooCommerce products are forced to the block editor. 

Looks like the issue is that for post types that are not edited with githuber-md markdown, this plugin tries to explicitly enable the Gutenberg editor. This happens for post types that are (a) not built in, (b) public and (c) are shown in REST api. This happens to include WooCommerce products.
