### ISSUE TITLE
[Feature Request] Override cmd + B default behavior on Firefox 

### ISSUE THREAD

**Issue by edoreld** [terrylinooo/githuber-md#25]
Browser: Firefox
OS: Mac

**What I want to happen:**
When editing a post, I want to be able to use the "cmd + B" shortcut to make the selected text bold.

**What actually happens:**
Firefox's Bookmark Manager opens.

**What needs to change:**
The plugin should override Firefox's shortcut just like the Guttenberg editor does.

**Comment by terrylinooo** [comment]
@edoreld 
Thanks for your suggestions.
Keyboard shortcut is good idea. This feature is scheduled in version 1.7.0.
I have to consider the most condition for not only Mac users but also Windows users, including Chrome, Firefox and other browsers. I will make it in Githuber MD, but not the next version, because I need time to do some research.

**Comment by terrylinooo** [comment]
My idea is that I will create a new tab in plugin's setting page and name it with "Shortcut".
Define some default settings on thoses shortcuts, and user is able to change the shortcut keys they want.

**Comment by edoreld** [comment]
I prefer that to my own idea as your suggestion would also be future proof in case a browser sneakily chances shortcuts (unlikely, but still...)
