### ISSUE TITLE
無法顯示語法高亮功能

### ISSUE THREAD

**Issue by kirin-lin** [terrylinooo/githuber-md#289]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

在安裝新版的 Wordpress (6.0 及 5.9.4) 中，語法高亮功能無法正常顯示。

**如何重現**

請告知重現此問題的步驟回何：

1. 安裝新版的 Wordpress (6.0 或 5.9.4)
2. 啟用 githuber-md 模組
3. 啟用語法高亮功能
4. 建立新文章，加入程式碼區塊

**預期的行為或結果**
理論上程式碼會出現彩色的字型，但是卻沒有出現。不管是用 prism.js 或是 highlight.js 都無法正常。
在預覽時，程式碼高亮的功能可以正常顯示。

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**
![1663409653652](https://user-images.githubusercontent.com/6138549/190851780-61820065-58f3-4f49-aa09-88be480f38d9.jpg)

![1663409700381](https://user-images.githubusercontent.com/6138549/190851793-8b682b37-c375-477f-af56-1dc18b611b93.jpg)

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**
ubuntu 20 + apache2

 - WordPress 版本: 5.9.4 或 6.0.2
 - WP Githuber MD 版本: 1.16.1
 - PHP 版本: 8.1.8

**用戶端環境**
 - 作業系統: macos 12.5.1
 - 瀏覽器: chrome, firefox

**其它說明**

如果有的話，請提供。

**Comment by guoqqqi** [comment]
hello, @kirin-lin  I had the same problem not long ago, you should go to the console and check your style theme:
![image](https://user-images.githubusercontent.com/72343596/192106392-69e969d8-6c88-4854-a024-a86643da328b.png)
You should then mark your block language, otherwise, the default style will be used.

**Comment by wyj3931** [comment]
@kirin-lin @guoqqqi  我也遇到了这个问题，后台都设置好了，但是没有高亮。在网上搜到这样一条微博，不知道是不是Bug。https://m.weibo.cn/status/4769749390855314
