### ISSUE TITLE
Cannot get you my sign of appreciation

### ISSUE THREAD

**Issue by adriatic** [terrylinooo/githuber-md#64]
Being genuinely excited seeing that you have all of the MD features in your plugin, which I would have implemented had I been the author, I wanted to send you $10. Well, there seem to be a problem between you and PayPal as this screenshot will explain:

![image](https://user-images.githubusercontent.com/2712405/57257801-7ecede00-7028-11e9-9645-e04c1edfc4c2.png)

**Comment by terrylinooo** [comment]
@adriatic 
First of all, I am glad you like this plugin and thank you so much for your encouragement. 
I have contacted PayPal support, not sure about the result.
If PayPal doesn't allow my account to receive the donation, you can "Star" this project on GitHub (It is kind of the "Like" button of Facebook) or leave a positive review on the plugin review. One of both is also a big encouragement for me because money is not my first concern, I make for interest and I like to see people love it.

**Comment by christophcemper** [comment]
@terrylinooo I'm probably one of the early users, and I LOVE you're plugin

Just starred it, and will write my first Wordpress plugin review for you now.

**Comment by christophcemper** [comment]
And let me know when the PayPal thing works again.

**Comment by christophcemper** [comment]
Actually even had to create an account for it, after 10 or so years of Wordpress :-D

![image](https://user-images.githubusercontent.com/12080594/57281577-8edbd180-70ab-11e9-9bf0-94a09aafc227.png)

**Comment by terrylinooo** [comment]
Thank you.
